- name: Update all packages
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true
  become: true

- name: Install system packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  become: true

- name: include the konstruktoid.docker_rootless role
  ansible.builtin.include_role: 
    name: konstruktoid.docker_rootless
  vars:
    docker_user: "{{ docker_username }}"

- name: Install Python modules
  ansible.builtin.pip:
    name: "{{ pip_packages }}"
    state: present