{
 "title": "Example dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM threads",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(jvm_threads_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "JVM memory committed total",
   "type": "stat",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_committed_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM memory pools usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_committed_bytes",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Http responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "rate(http_response_total[1m])", "legendFormat": "{{endpoint}} code: {{status}}" }
   ]
  }
 ]
}