- name: register "{{ docker_user }}" info
  become: "yes"
  user:
    name: "{{ docker_user }}"
  check_mode: "yes"
  register: docker_user_info

- name: Deploy Postgre container
  community.docker.docker_container:
    name: mealie-db
    image: "{{ image }}"
    state: started
    restart_policy: always
    ports:
      - "{{ docker_port }}"
    env:
      POSTGRES_PASSWORD: "{{  POSTGRES_PASSWORD }}"
      POSTGRES_USER: "{{ POSTGRES_USER  }}"
      POSTGRES_DB: "{{ POSTGRES_DB }}"
    volumes:
      - "data:/var/lib/postgresql/data"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ docker_user_info.uid }}"
    PATH: "{{ docker_user_info.home }}/bin:{{ ansible_env.PATH }}"
    DOCKER_HOST: "unix:///run/user/{{ docker_user_info.uid }}/docker.sock"
  no_log: true
