version: "3.9"
services:
  prometheus:
    image: prom/prometheus:v2.40.7
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - "prometheus_training_data:/prometheus"
      - "./myrules.yml:/etc/prometheus/myrules.yml"
      - "./alerts.yml:/etc/prometheus/alerts.yml"
  node_exporter:
    image: prom/node-exporter:v1.5.0
    ports:
      - "9100:9100"
  app:
    image: paweljpl/monitoring-test-app:0.0.1
    ports:
      - "8080:8080"
      - "9095:9095"

volumes:
  prometheus_training_data:
