version: "3.9"
services:
  prometheus:
    image: prom/prometheus:v2.40.7
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - "prometheus_training_data:/prometheus"

volumes:
  prometheus_training_data:
