---
- name: Create Azure VM
  hosts: localhost
  connection: local
  vars_files:
    - vars_azure_vm.yml
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: "{{ name_prefix }}-rg"
        location: "{{ location }}"

    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ name_prefix }}-rg"
        name: "{{ name_prefix }}-vnet"
        address_prefixes: "{{ ip_range }}"

    - name: Create Network Security Group that allows SSH
      azure_rm_securitygroup:
        resource_group: "{{ name_prefix }}-rg"
        name: "{{ name_prefix }}-nsg"
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
          - name: HTTP
            protocol: Tcp
            destination_port_range: 80
            access: Allow
            priority: 1002
            direction: Inbound

    - name: Add subnet
      azure_rm_subnet:
        resource_group: "{{ name_prefix }}-rg"
        name: "{{ name_prefix }}-subnet"
        address_prefix: "{{ ip_range }}"
        virtual_network: "{{ name_prefix }}-vnet"
        security_group_name: "{{ name_prefix }}-nsg"

    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: "{{ name_prefix }}-rg"
        allocation_method: Static
        name: "{{ item }}-pip"
      loop: "{{ vm_list }}"
      register: output_ip_address

    - name: Public IP of VM
      ansible.builtin.debug:
        msg: "The public IP is {{ item.state.ip_address }}."
      loop: "{{ output_ip_address.results }}"
      loop_control:
        label: "{{ item.item }}"

    - name: Create virtual network interface card
      azure_rm_networkinterface:
        resource_group: "{{ name_prefix }}-rg"
        name: "{{ item.item }}-nic"
        virtual_network: "{{ name_prefix }}-vnet"
        subnet: "{{ name_prefix }}-subnet"
        create_with_security_group: false
        ip_configurations:
          - name: ipconfig
            public_ip_address_name: "{{ item.state.name }}"
            primary: true
      loop: "{{ output_ip_address.results }}"
      loop_control:
        label: "{{ item.item }}"

    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: "{{ name_prefix }}-rg"
        name: "{{ item }}"
        vm_size: Standard_B1s
        admin_username: ansible
        ssh_password_enabled: false
        ssh_public_keys:
          - path: /home/ansible/.ssh/authorized_keys
            key_data: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCXtly/QMTfCYto69Fk7yfMzeH4QXzADEtkXmicq3/PJXYzi1nhzZnBkgGozXJ4wBwrkY0GEMuJ0J1qzRNQsEDgNij90pYZXCUr3pCnvEFHeTu+36SKoe+ktYIp5eeWBAgTH9Z3pb64ayzmlyDBpVxpR93BXjb7Hq246ruxPd/BFVH5AlsnMNBoxCfGaLwx1tgUpivzZfIayyQOx/gqYt3uWnJhTOEv37JRRPyf3M5gUor+mI4W6NwhPCuQRrx9OuD/e3UxKSVlbm4pPiAbgMq/nMttE4VTGo8WSue3h1bIqZIXB+J4TdQBnNV+B1w6R91icX6jVuYHj95/Eb0qEGbOLbc7f17j3fc3q+OkrRcNd+EUGBFzJR7csAAzEApfGspPjxNlSDgO5nuhNEb0/yONqWAXIQqMJI8BTCZC+1ZmKQeWtu6MC9xOEpB18djNGGRo4vcu4dEZIWdx+TUn0G+SweZTmiY4jon2lwUKKWKy7oV/+WA/J4cuure56ZyOwSU= vagrant@ansible"
        network_interfaces: "{{ item }}-nic"
        image:
          offer: 0001-com-ubuntu-server-focal
          publisher: Canonical
          sku: 20_04-lts-gen2
          version: latest
        managed_disk_type: Standard_LRS
      loop: "{{ vm_list }}"
