apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  defaultBackend:
    service:
      name: frontend-service
      port:
        number: 80
  rules:
    - http:
        paths:
          - backend:
              service:
                name: frontend-v2-service
                port:
                  number: 81
            pathType: Prefix
            path: /v2
    - http:
        paths:
          - backend:
              service:
                name: frontend-service
                port:
                  number: 80
            pathType: Prefix
            path: /v1
