Vagrant.configure("2") do |config|
    config.vm.box_check_update = true
    config.vm.box = "ubuntu/focal64"
    config.vm.synced_folder ".", "/vagrant", :mount_options => ["umask=077"]
  
    config.vm.define "ansible" do |ansible|
        ansible.vm.hostname = "ansible"
        ansible.vm.network "private_network", ip: "10.0.0.5"

        ansible.vm.provider "virtualbox" do |vb|
            vb.name = "ansible"
            vb.cpus = "2"
            vb.memory = "2048"
        end
    end

    config.vm.define "node1" do |node1|
        node1.vm.hostname = "node1"
        node1.vm.network "private_network", ip: "10.0.0.11"

        node1.vm.provider "virtualbox" do |vb|
            vb.name = "node1"
            vb.cpus = "1"
            vb.memory = "1024"
        end
    end

    config.vm.define "node2" do |node2|
        node2.vm.hostname = "node2"
        node2.vm.network "private_network", ip: "10.0.0.12"

        node2.vm.provider "virtualbox" do |vb|
            vb.name = "node2"
            vb.cpus = "1"
            vb.memory = "1024"
        end
    end

    config.vm.define "node3" do |node3|
        node3.vm.box = "centos/8"
        node3.vm.hostname = "node3"
        node3.vm.network "private_network", ip: "10.0.0.13"

        node3.vm.provider "virtualbox" do |vb|
            vb.name = "node3"
            vb.cpus = "1"
            vb.memory = "1024"
        end
    end
end
